### ISSUE TITLE
Within page links not working well

### ISSUE THREAD

**Issue by richardtheprince** [marcoscgdev/LocalHTMLViewer#1]
If you have a page with section hyperlinks, and you use a link to go to a section, once you click another link to go to another section, you end up on a random spot on the page

**Comment by marcoscgdev** [comment]
Several users have reported this problem to me. I'm investigating about it.

This is not a solution, but it can prevent the problem in your html document. Simply add this code to it:
`

<script src="https://code.jquery.com/jquery-1.12.4.min.js"></script>

<script>
$(document).on('click', 'a[href^="#"]', function (event) {
    event.preventDefault();
    $('html, body').animate({
        scrollTop: $($.attr(this, 'href')).offset().top
    }, 500);
});
</script>
`

**Comment by richardtheprince** [comment]
Nice, thanks!

**Comment by marcoscgdev** [comment]
After a long research I can confirm that It is an Android WebView relative bug. The code posted previously is the only solution to the problem that I can give.

**Comment by richardtheprince** [comment]
Aha too bad. In any case, great work!

________________________________
Van: Marcos Calvo García <notifications@github.com>
Verzonden: Monday, June 18, 2018 2:13:57 PM
Aan: marcoscgdev/LocalHTMLViewer
CC: richardtheprince; Author
Onderwerp: Re: [marcoscgdev/LocalHTMLViewer] Within page links not working well (#1)


After a long research I can confirm that It is an Android WebView relative bug. The code posted previously is the only solution to the problem that I can give.
