### ISSUE TITLE
AngularJS(?) broken after last update

### ISSUE THREAD

**Issue by lanierd2** [marcoscgdev/LocalHTMLViewer#3]
I have an angularJS code that doesn't work after the latest update--the same file works fine on other applications and worked fine before the update, but now it's broken :( Please fix, because your app is very useful otherwise!

**Comment by marcoscgdev** [comment]
Hello,

Can you specify the app version number? You can help me fixing the bug by sending the html file.

Thanks for reporting it :)

**Comment by lanierd2** [comment]
The issue arose in version 1.2.3 (Android)--HTML file is attached. I'm
pretty new to web programming so it's likely that there's something weird
about my code, but it works on other apps and it worked on yours prior to
the last update :) thanks!

**Comment by marcoscgdev** [comment]
Hi,

I have updated the app with a possible fix for your issue. Please, confirm me if after updating the app the issue keeps happening.

Thanks.

**Comment by lanierd2** [comment]
That did the trick! Thanks so much for the quick fix :)

**Comment by marcoscgdev** [comment]
You are welcome :smile:
