### ISSUE TITLE
Opening .mht file results in garbage output

### ISSUE THREAD

**Issue by d3BugErr** [marcoscgdev/LocalHTMLViewer#5]
So as title says, on my old android 4.1.1 tab opening any .mht file results in nonsensical garbage being displayed that look like result of some unicode conversion issue. All the same files are opened okay under same version of the application on my phone (android 6).
Any ideas whether this is fixable?

mht file is open
![screenshot_2019-02-03-21-44-26](https://user-images.githubusercontent.com/25364850/52181108-57852c80-27ff-11e9-801b-7bd8ad296047.png)

sys info
![screenshot_2019-02-03-21-44-48](https://user-images.githubusercontent.com/25364850/52181107-57852c80-27ff-11e9-94ee-a3bd6d7e6951.png)

**Comment by marcoscgdev** [comment]
Maybe the problem can be in the internal device's webview. Try to install this webview in your device https://play.google.com/store/apps/details?id=com.google.android.webview and set it as the default webview inside the developer settings.

**Comment by d3BugErr** [comment]
Sorry for late reply and thanks for your suggestion.
Alas webview updates become a thing only since Android 5. And this one tablet is quite old, so no firmware updates are out there to upgrade from Android 4.
Guess I'll have to settle with reading my .mht library on other devices.
